### ISSUE TITLE
Not work on Windows 10, Emacs 25.1

### ISSUE THREAD

**Issue by alexei-28** [HKey/dired-atool#2]
` Window 10, Emacs 25.1, Helm, dired+, dired-atool 20160208.433`

I install dired-atool by `package-list-package`
In my **init.el** 

```
(require 'dired+)
(setq ls-lisp-dirs-first t)
(dired-atool-setup)
```

So I want to pack 2 mark files from directory `d:\TEMP\test\from_this\` to directory `d:\TEMP\test\to\`

Here steps:

Step#1

![step1](https://user-images.githubusercontent.com/303539/32143908-ac884288-bcb9-11e7-92e2-670208ad15f5.png)

`M-x dired-atool-do-pack`

Step#2 
![step2](https://user-images.githubusercontent.com/303539/32143912-bef0526c-bcb9-11e7-86c4-42f30e4397df.png)

Press **Enter** and I get message:

![step3](https://user-images.githubusercontent.com/303539/32143916-c982affe-bcb9-11e7-8707-04b440b1a99d.png)

If I answer **NO** then I get message:

`Packing canceled.`

If I answer **YES** then I get message:

`Removing old name: is a directory: d:/TEMP/test/to/`

In both cases **NOTHING** happend. Files are **NOT** packaged

**Comment by HKey** [comment]
@lmdic I'm sorry for late reply.

`dired-atool-do-pack` needs an archive file name to create, not a directory name.

Currently `dired-atool-do-pack` only can pack files into an archive file.
So, if you want to pack them into an archive file "packed.zip", please enter like bellow:

`Pack * [2 files] to: d:/TEMP/test/to/packed.zip`

Thank you for the detailed report.

**Comment by alexei-28** [comment]
Not help. After I `dired-atool-do-pack` it ask my to create new directory **packed.zip**

![dired-atool](https://user-images.githubusercontent.com/303539/36915677-3f2bb348-1e5a-11e8-9c21-34f05323590e.png)

If **yes** it create directory **package.zip** - but not archive **packed.zip**

and here output:

```
'"atool"' is not recognized as an internal or external command,
operable program or batch file.
```

![step](https://user-images.githubusercontent.com/303539/36915654-27506b24-1e5a-11e8-8098-c1651eb0c9ec.png)

**Comment by HKey** [comment]
I've updated dired-atool.
Can you try it?

> '"atool"' is not recognized as an internal or external command,
> operable program or batch file.

Hmm, it looks like `atool` command is not installed.
Does `atool` command exist on your system?

**Comment by alexei-28** [comment]
I get `dired-atool` from melpa

`dired-atool        20160208.433  available  melpa      Pack/unpack files with atool on dired.`

As you can see , the version is old.

1. The vesion is not update
2. I'm not has `atool `in my system. Where I can find it for Windows 10 (64 bit)?

**Comment by HKey** [comment]
> 1. The vesion is not update

Yes. Melpa's update takes about 4 hours recently.
dired-atool will be updated later.

> 2. I'm not has atool in my system. Where I can find it for Windows 10 (64 bit)?

Sorry, I don't know that.
As far as I know msys2 may help you.

**Comment by alexei-28** [comment]
After update it's almost work. I need to install **atool** for Windows. Because I get error:

```
'"atool"' is not recognized as an internal or external command,
operable program or batch file.

D:/Programs/emacs/libexec/emacs/25.1/x86_64-w64-mingw32/cmdproxy.exe -c "atool" "--add" "d:/TEMP/test/to/myarc.zip" "--explain" "how_replace.txt" exited with code 1 at Sat Mar  3 20:15:19 2018
```

**Comment by HKey** [comment]
Thanks.
Yes, you need to install atool to use dired-atool.
